version: '3.9'
name: gamehub
services:
  postgresql:
    image: docker.io/bitnami/postgresql:latest
    container_name: postgresql
    ports:
      - "5435:5432"
    environment:
      - POSTGRESQL_PASSWORD=postgres
    volumes:
      - './pg_data:/bitnami/postgresql'
    networks:
      - software
  opensearch:
    image: 'bitnami/opensearch:latest'
    ports:
      - "9300:9300"
      - "9200:9200"
    environment:
      - OPENSEARCH_PASSWORD=bitnami
    volumes:
      - './opensearch_data:/bitnami/opensearch/data'

  keycloak:
    image: docker.io/bitnami/keycloak:latest
    container_name: keycloak
    ports:
      - "80:8080"
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_HOST=postgresql
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_NAME=gamehub
      - KEYCLOAK_DATABASE_SCHEMA=keycloak
      - KEYCLOAK_DATABASE_USER=postgres
      - KEYCLOAK_DATABASE_PASSWORD=postgres
    depends_on:
      - postgresql
    volumes:
      - './keyckloak_data:/opt/bitnami/keycloak/data'
    networks:
      - software

#  liquibase:
#    image: liquibase:0.1
#    container_name: migrations
#    environment:
#      - URL=jdbc:postgresql://postgresql:5432/load_testing
#      - USERNAME=admin
#      - PASSWORD=admin
#    depends_on:
#      - postgresql
#    networks:
#      - software

networks:
  software:
    driver: bridge